server:
  port: 8080

spring:
  application:
    name: javahub-backend
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: 27017
      database: javahub

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
